---
title: 'Data Tidying: ICPMS'
author: "James Vesto"
date: "12/16/2019"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
#This is the setup chunk
knitr::opts_chunk$set(echo = TRUE)
#The two packages being used in this code are tidyverse and readr, both are available on CRAN and can be installed if necessary with the following lines of code:

#install.packages("tidyverse")
#install.packages("readr")
#install.packages("janitor")

#loading the libraries
library(tidyverse)
library(readr)
library(janitor)

```

1) Importing the Data
```{r, warning=FALSE, message=FALSE}
#Before running this code make sure to upload the data onto the RStudio server 
#or save the data files in an appropriate location for desktop versions of R
#To resolve error messages about the data path set the working directory as the location where the data is saved.

#The example calls the full path, this will need to be changed to however the data is saved on your computer. An easy way to determine the path is to click the import dataset button in the environment and copy the path from the box on the top.

ICPMS_imported <- read.csv("~/RStudio/Projects/Chem311_JCWS/data/ICPMS_Data.csv", 
                           skip=1, 
                           na="N/A")
sample_key <- read.csv("~/RStudio/Projects/Chem311_JCWS/data/Sample_Key.csv", skip=0)

#Preview data
ICPMS_imported
sample_key
```

#Data Tidying

2) Tidying the RSD Data
```{r Tidying RSD Data, warning=FALSE, message=FALSE}
#This code chunk tidies the ICPMS RSD data
#this is done separately from the overall data tidying to ensure the RSD values 
#are properly matched to the correct sample reading (CPS)

RSD_data<-ICPMS_imported %>%
  #first the RSD columns are selected 
  #and renamed with the appropriate metal isotope
  select(Cr52 = CPS.RSD, 
         Cr53 = CPS.RSD.1, 
         As75 = CPS.RSD.2, 
         Cd111 = CPS.RSD.3, 
         Cd114 = CPS.RSD.4, 
         Pb208 = CPS.RSD.5,
         Ge_RSD = CPS.RSD.7,
         Sample.Key)%>% 
  #The sample key is also selected for later use in verifying 
  #that the RSD data is properly matching the CPS Data
  #then the newly renamed RSD columns are gathered together and 
  #a column is created to indicate which metal corresponds to which RSD
  pivot_longer(1:6,
               names_to = "metal",
               values_to="RSD")

#Previewing the Tidy RSD Data
RSD_data
```

3) Tidying the CPS Data & Correcting for ISTD
```{r CPS ICPMS Tidying}
#Tidying the CPS Data for ICPMS and combining back in the RSD data
ICPMS_tidy <- ICPMS_imported %>% 
  select(Cr52 = CPS,
         Cr53 = CPS.1,
         As75 = CPS.2,
         Cd111 = CPS.3,
         Cd114 = CPS.4,
         Pb208 = CPS.5,
         Ge72 = CPS.7,
         Sample.Key)%>% 
  pivot_longer(1:6,
               names_to= "metal", 
               values_to= "CPS")%>% 
  #mutating in the RSD data
  mutate(RSD = RSD_data$RSD/RSD_data$Ge_RSD,
         CPS=CPS/Ge72)%>%#ISTD Correction
  select(-Ge72)

#Confirming that the RSD data properly matches the CPS data
#Should output TRUE if the data is properly matching 
all(RSD_data$Sample.Key==ICPMS_tidy$Sample.Key, RSD_data$metal==ICPMS_tidy$metal)

#Previewing the ICPMS Data
ICPMS_tidy
```

4) Merging in the Sample Key
```{r merging sample key}
#Merging together the ICPMS Data and the Sample Key
ICPMS <- merge(ICPMS_tidy, sample_key)%>%
  clean_names()

#Previewing the merged data
ICPMS

write.csv(ICPMS,file="~/RStudio/projects/Chem311_JCWS/data/ICPMS_tidy_example.csv")
```

5) Removing clutter from the environment!

```{r, warning= FALSE}
#Set warning=FALSE so the chunk will not notify you when an object is already removed from the environment
rm(list=setdiff(ls(), "ICPMS"))
```

#See file 2 for the ICPMS data analysis example code!