---
title: 'Data Tidying: ICPMS'
author: "James Vesto"
date: "12/16/2019"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
```

```{r}
#Note! Before running this file you must run file 1 (01_ICPMS_data_tidying.Rmd)
ICPMS
```

1) Start by defining useful lists; such as what sites, metals, and sample IDs were analyzed.

```{r}
sample_sites <- unique(filter(ICPMS, site!= "QC", site!="MB", site!="")$site)
#excluding method blank and quality control from the list of sites
metals_analyzed <- unique(ICPMS$metal)
analysts <- unique(filter(ICPMS, analyst!="")$analyst)

#Preview the lists to check for potential issues:
#sample_sites
#analyst
#metals_analyzed
#unique_IDs #from file 1
```

2) Calibrating the ICPMS Data

```{r Calibration}

ICPMS_cal <- NULL

for (unique_metal in metals_analyzed){

  cal <- ICPMS %>% 
      filter(type == "Cal1" | type== "Cal2" | type == "Cal3") %>% 
      filter(metal == unique_metal) %>%
      select(conc = concentration, signal = CPS.corrected, RSD = RSD.corrected) #(Kg/mL)

  w <- 1/(cal$signal*cal$RSD)^2 
  model <- lm(cal$signal ~ cal$conc, weights= w)

  slope <- model$coefficients[2]
  intercept <- model$coefficients[1]
  slope.STD <- summary(model)$coefficients[2,2]
  intercept.STD <- summary(model)$coefficients[1,2]

  plot(cal$signal ~ cal$conc,
      xlab= paste("Concentration of ", unique_metal,"(ppb)"),
      ylab= "Counts per second")+ 
      abline(model, col="red")+ 
      title(paste("Calibration for", unique_metal)) 

  equation <- data.frame(metal= unique_metal, slope, slope.STD, intercept, intercept.STD)
  ICPMS_cal <- rbind(ICPMS_cal, equation)
  }

ICPMS_cal
  
  #Clearing the environment (optional, but helps to prevent accidentally using the wrong object!)
  remove(equation, cal, slope, slope.STD, intercept, intercept.STD, w, model, unique_metal)
```

2) Creating a function to analyze samples
```{r}
#inputs: unique_site (as a character, ex. "A")
#outputs: concentration vector (containing: Metal, site, )

sample_analysis <- function(unique_site){
  concentration_data <- NULL
  
  for (unique_metal in metals_analyzed){
    sample_data <- filter(ICPMS, metal == unique_metal, site == unique_site) 
    cal <- filter(ICPMS_cal, metal == unique_metal) 
  
    m <- cal$slope 
    b <- cal$intercept 
    y <- sample_data$CPS.corrected
  
    intercept.error <- cal$intercept.STD
    slope.error <- cal$slope.STD
  
    x <- (y-b)/m #The units are dependent on the calibration standards (Kg/mL)
    
    if(unique_site=="MB"){
      x <- mean(x)}
  
    concentrations <- data.frame(sample.key = sample_data$sample.key, 
                                analyst=sample_data$analyst,
                                metal= unique_metal,
                                site = unique_site,
                                concentration.diluted=x, 
                                intercept.error, 
                                slope.error)
    
    concentration_data <- rbind(concentration_data, concentrations)}
  return(concentration_data)}

```

3) Creating a run_sites function
```{r}
#inputs: a function
#outputs: a data frame with the function outputs from each site
run_sites <- function(Function){
  value <- NULL
  for(sites in sample_sites){
    site_value <- Function(sites)
    value <- rbind(site_value, value)}
  return(value)
  }
```

4) Calibrate the data, perform a method blank, and correct for dilution)

```{r}

#1) Calibrate data
MB <- sample_analysis("MB")

uncor_sample <- run_sites(sample_analysis)
keys <- unique(uncor_sample$sample.key)

#2) Method Blank
sample_data <- NULL

for (unique_metal in metals_analyzed){
  MB_metal <- filter(MB, metal==unique_metal)%>%
    select(-sample.key,-analyst)%>%
    unique()
  
  for(ID in keys){
  sample_metal <- filter(uncor_sample, metal==unique_metal)
  metal_sample_data <- mutate(sample_metal, 
                              conc.dil.blanked = sample_metal$concentration.diluted-MB_metal$concentration.diluted)
  sample_data<- rbind(sample_data, metal_sample_data)
  }}

#3) Correct for dilution
sample_data <- merge(ICPMS,sample_data)%>%
  unique()%>%
  mutate(conc.blanked= conc.dil.blanked*(total.volume/1000)/(mass.soil/1000*1000)*101)%>%
  mutate(conc.unblanked= concentration.diluted*(total.volume/1000)/(mass.soil/1000*1000)*101)%>%
  select(-concentration,-type)

sample_data

#4) Clean environment
remove(unique_metal, MB_metal, metal_sample_data, MB, uncor_sample, ID, keys, sample_metal)

```

5) error propogation